module.exports = {
	USERS_SERVICE_HOST: 'localhost',
	USERS_SERVICE_PORT: 8080,
	USERS_SERVICE_DB: 'users_service',
	USERS_SERVICE_DB_HOST: 'localhost',
	USERS_SERVICE_DB_PORT: 5432,
	USERS_SERVICE_DB_USERNAME: 'postgres',
	USERS_SERVICE_DB_PASSWORD: 'masterpassword',
	
	HISTORY_SERVICE_HOST: 'localhost',
	HISTORY_SERVICE_PORT: 8081,
	HISTORY_SERVICE_DB: 'history_service',
	HISTORY_SERVICE_DB_HOST: 'localhost',
	HISTORY_SERVICE_DB_PORT: 5432,
	HISTORY_SERVICE_DB_USERNAME: 'postgres',
	HISTORY_SERVICE_DB_PASSWORD: 'masterpassword',
	HISTORY_SERVICE_PAGE_SIZE: 10,
}